server:
  #\u9ED8\u8BA48080
  port:
#\u6570\u636E\u5E93\u914D\u7F6E
#\u544A\u8BC9\u5E94\u7528\u7A0B\u5E8F\u4F7F\u7528driver-class-name\u8FD9\u4E2A\u9A71\u52A8\u7C7B\u6765\u4E0EMySQL\u6570\u636E\u5E93\u901A\u4FE1
spring:
  datasource:
    #\u6570\u636E\u5E93\u8FDE\u63A5\u5730\u5740
    url: jdbc:mysql://localhost:3306/auction?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
    username: root
    #\u6570\u636E\u5E93\u5BC6\u7801
    password: 123456
    #\u6570\u636E\u5E93\u9A71\u52A8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  ##映射xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #配置文件
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #数据库中的表名与实体类名的映射关系(下划线命名法转驼峰命名法)
    map-underscore-to-camel-case: true